dataset: tiered
arch: wrn_s2m2
checkpoint: "s2m2/tiered/wrn_s2m2.ckpt"
cache_dir: "s2m2/tiered/wrn_s2m2"
use_cached: true

n_shots: 1

embedding: nohubs
nohubs:
  different_label_exaggeration: 5
  kappa: 0.5
  loss_weights: [0.25]
  out_dims: 400
  perplexity: 40
