dataset: tiered
arch: wrn_s2m2
checkpoint: "s2m2/tiered/wrn_s2m2.ckpt"
cache_dir: "s2m2/tiered/wrn_s2m2"
use_cached: true

n_shots: 5

embedding: nohubs
nohubs:
  different_label_exaggeration: 12
  exaggeration_mode: linear
  kappa: 0.2
  loss_weights: [0.15]
  out_dims: 400
  perplexity: 35
